//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3.ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOUE
    {
        public decimal NB_KM { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
        public Nullable<int> CLIENT { get; set; }
        public Nullable<int> VEHICULE { get; set; }
        public int ID { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual VEHICULE VEHICULE1 { get; set; }
    }
}
