//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikyASPAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICLE()
        {
            this.COMMENTAIRE = new HashSet<COMMENTAIRE>();
        }
    
        public int id { get; set; }
        public string theme { get; set; }
        public string auteur { get; set; }
        public string contenue { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string image { get; set; }
        public string utilisateur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTAIRE> COMMENTAIRE { get; set; }
        public virtual PERSONNE PERSONNE { get; set; }
    }
}
